production:
  adapter: postgresql
  host: ec2-54-225-101-18.compute-1.amazonaws.com
  database: dejltlsfg5l08v
  port: 5432
  pool: 5
  encoding: unicode
  timeout: 5000
  username: drodxpbzyheasv
  password: oqOR4bLxEwAaaz9sIZswOu2VmS
